"""
Django settings for typelearn project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-$vf+xelyc3(54jvin_er6edu7(iq89+@xd!hp@vz2fmzc$wym4',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() != 'false'

# The Gateway forwards the browser's Host header, and in-cluster probes arrive
# on the pod IP, so the list has to come from the environment rather than name
# the two loopback spellings a host-run runserver used to see.
ALLOWED_HOSTS = [
    host
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'exercises',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Directly after SecurityMiddleware and before everything else, where
    # WhiteNoise's own documentation puts it: a static file is then answered
    # without the session, auth and message middleware running for it.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'typelearn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'typelearn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'typelearn'),
        'USER': os.environ.get('POSTGRES_USER', 'typelearn'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Collected into the image at build time and served from there by WhiteNoise, in
# every environment — the admin is unstyled otherwise anywhere DEBUG is off.
# Nothing mounts over this path: collecting at pod start would make every replica
# repeat the work, make readiness wait on it, and let two replicas of one image
# disagree about what they serve.
#
# The ingested clips are deliberately not served this way. They are written at
# runtime and read once per exercise, and WhiteNoise builds its file index at
# startup unless DEBUG is on — so a clip ingested after the pod started would
# 404 until it restarted. A web server holds them instead; see
# chart/templates/media-server.yaml.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise adds `Access-Control-Allow-Origin: *` to every static response
# unless told not to. This application is served from exactly one origin, on
# purpose, and carries no CORS configuration anywhere — a permission granted
# because a library defaults to it is still a permission the application comes
# to depend on. Nothing here is fetched cross-origin, including the admin's own
# CSS, so nothing needs it.
WHITENOISE_ALLOW_ALL_ORIGINS = False


# Media files (audio clips copied from the corpus at ingestion)
# https://docs.djangoproject.com/en/6.1/topics/files/

MEDIA_URL = '/media/'

# A volume in the cluster, and a directory beside the code when a management
# command runs on the host. Either way the clips live outside the image.
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# GraphQL query limits
# Guards against oversized, alias-bombed, or deeply nested documents. Read from
# the environment so a deployment can tighten or loosen them without a code
# change. GraphiQL's introspection query fits inside the token default, and the
# depth limiter ignores introspection fields, so development is unaffected.

STRAWBERRY_MAX_TOKENS = int(os.environ.get('STRAWBERRY_MAX_TOKENS', 1000))
STRAWBERRY_MAX_ALIASES = int(os.environ.get('STRAWBERRY_MAX_ALIASES', 10))
STRAWBERRY_MAX_QUERY_DEPTH = int(os.environ.get('STRAWBERRY_MAX_QUERY_DEPTH', 10))
