# Generated by Django 6.1 on 2026-08-22 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=255, unique=True)),
                ('sentence_id', models.CharField(blank=True, max_length=64)),
                ('original_audio', models.FileField(upload_to='clips/')),
                ('up_votes', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='exercises.exercise')),
            ],
            options={
                'verbose_name_plural': 'progress',
            },
        ),
    ]
