# Generated by Django 6.1.1 on 2026-09-26 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=500)),
                ('origin', models.CharField(choices=[('machine', 'Machine'), ('learner', 'Learner')], max_length=16)),
                ('status', models.CharField(choices=[('published', 'Published'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=16)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('client_id', models.CharField(blank=True, max_length=64)),
                ('address_hash', models.CharField(blank=True, max_length=64)),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='exercises.exercise')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TranslationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('address_hash', models.CharField(blank=True, max_length=64)),
                ('value', models.SmallIntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='exercises.translation')),
            ],
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['exercise', 'language', 'status'], name='translation_lookup'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['client_id', 'created_at'], name='translation_by_client'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['address_hash', 'created_at'], name='translation_by_address'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'machine')), fields=('exercise', 'language'), name='one_machine_translation_per_language'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('exercise', 'language', 'text'), name='unique_translation_text'),
        ),
        migrations.AddIndex(
            model_name='translationrating',
            index=models.Index(fields=['client_id', 'updated_at'], name='rating_by_client'),
        ),
        migrations.AddIndex(
            model_name='translationrating',
            index=models.Index(fields=['address_hash', 'updated_at'], name='rating_by_address'),
        ),
        migrations.AddConstraint(
            model_name='translationrating',
            constraint=models.UniqueConstraint(fields=('translation', 'client_id'), name='one_rating_per_client'),
        ),
    ]
